// <auto-generated />
using System;
using API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Entities.Technician", b =>
                {
                    b.Property<Guid>("TechnicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("TechnicianId");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            TechnicianId = new Guid("d88c457f-4513-402c-9b12-b6a0418fb06c"),
                            FirstName = "yaseen",
                            LastName = "Ahmed",
                            Status = true
                        },
                        new
                        {
                            TechnicianId = new Guid("d50d48f3-096c-4b0a-8152-43ed4d2b86ad"),
                            FirstName = "Karan",
                            LastName = "Lala",
                            Status = true
                        },
                        new
                        {
                            TechnicianId = new Guid("47aee500-1bc3-4e7b-a590-13641c934cb5"),
                            FirstName = "yaseen",
                            LastName = "Ahmed",
                            Status = false
                        });
                });

            modelBuilder.Entity("API.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TechnicianRefId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("TechnicianId");

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            WorkOrderId = new Guid("45f925be-be1a-45ad-b930-097cc1e4f3f4"),
                            DateTime = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Bangalore Ramanagar"
                        },
                        new
                        {
                            WorkOrderId = new Guid("ce10c9a1-4e79-42e5-894b-fc38f0a055c5"),
                            DateTime = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Bangalore magadi"
                        },
                        new
                        {
                            WorkOrderId = new Guid("ddd0833d-f911-42d5-9909-ab77630d16ec"),
                            DateTime = new DateTime(2022, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Tumkur sira"
                        },
                        new
                        {
                            WorkOrderId = new Guid("b9193ebc-e41c-4b04-9841-8a95ec4cfd30"),
                            DateTime = new DateTime(2022, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Delhi kudur"
                        },
                        new
                        {
                            WorkOrderId = new Guid("a82a42b2-28bf-46de-8c92-cdef42daa19e"),
                            DateTime = new DateTime(2022, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Place = "Bangalore Kasargudu"
                        });
                });

            modelBuilder.Entity("API.Entities.WorkOrder", b =>
                {
                    b.HasOne("API.Entities.Technician", null)
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId");
                });

            modelBuilder.Entity("API.Entities.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
